### PR TITLE
CnnX0 implementation

### PR DESCRIPTION
**Pull request by jedrzejpolaczek**

### CODE REVIEW

**Comment by gmontamat** [comment]
Hi! Thanks for this contribution! I'll have time in Feb to work on some bugfixes for gentun, will gladly look forward to merging this too

**Comment by jedrzejpolaczek** [comment]
> Hi! Thanks for this contribution! I'll have time in Feb to work on some bugfixes for gentun, will gladly look forward to merging this too

Hi! Sorry for trouble! I am still working to add NSGA-Net, I will create new PR after I finish :)

**Comment by jedrzejpolaczek** [comment]
[gmontamat](https://github.com/gmontamat) may I please for contact information? I would like to contribute to your repository and discuss what I want to contribute and how to do it in the best way :)
My contact e-mail: jedrzej.polaczek@gmail.com

**Comment by gmontamat** [comment]
hi @jedrzejpolaczek I'll reach you out.

There's a roadmap to bring this library up to date: https://github.com/users/gmontamat/projects/1

Most important changes will be to update the branching strategy to [GitFlow](https://nvie.com/posts/a-successful-git-branching-model/) (so you would PR to develop not main), use of Redis instead of RabbitMQ for client-worker coordination, package it as a proper python lib and offer docker images for ease of deployment.

**Pull request closed without merging**
